services:
  - type: web
    name: crop-disease-detection
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    gitLfsEnabled: true
    envVars:
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
